language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  #- "nightly"
  - "pypy"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall -f .
  - pip install coveralls
  - coverage run --source=django_universal_view_decorator runtests.py
  #- python runtests.py
after_success:
  coveralls
notifications:
  email: false
