language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install coveralls
  # Under python3.2 the latest coverage fails with a syntax error this is why we downgrade to 4.0a5
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install --upgrade coverage==4.0a5; fi
script:
  - python -m compileall -f .
  - coverage run --source=django_universal_view_decorator setup.py test
after_success:
  coveralls
notifications:
  email: false
